- name: d8.operator.redis
  rules:
  - alert: D8RedisOperatorTargetDown
    expr: max by (job) (up{job="redis-operator"} == 0)
    for: 30m
    labels:
      severity_level: "8"
      tier: cluster
      d8_module: operator-redis
      d8_component: redis-operator
    annotations:
      plk_markup_format: markdown
      plk_protocol_version: "1"
      plk_labels_as_annotations: "instance,pod"
      plk_ignore_labels: "job"
      plk_create_group_if_not_exists__d8_prometheus_operator_unavailable: "D8RedisOperatorUnavailable,tier=cluster,redis=deckhouse,kubernetes=~kubernetes"
      plk_grouped_by__d8_prometheus_operator_unavailable: "D8RedisOperatorUnavailable,tier=cluster,redis=deckhouse,kubernetes=~kubernetes"
      description: |-
        The `redis-operator` Pod is not available.
        The new `redisfailover` settings cannot be applied in the cluster; however, all existing and configured components continue to operate correctly.
        This problem will not affect alerting or monitoring in the short term (a few days).
        The recommended course of action:
        1. Analyze the Deployment info: `kubectl -n d8-operator-redis describe deploy redis-operator`;
        2. Examine the status of the Pod and try to figure out why it is not running: `kubectl -n d8-operator-redis describe pod -l app=redis-operator`.
      summary: redis is unable to scrape `redis-operator` metrics.
