{{- define "redis_operator_resources" }}
cpu: 10m
memory: 25Mi
{{- end }}

{{- if (.Values.global.enabledModules | has "vertical-pod-autoscaler-crd") }}
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: redis-operator
  namespace: d8-operator-redis
  {{- include "helm_lib_module_labels" (list . (dict "app" "redis-operator")) | nindent 2 }}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: redis-operator
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: "redis-operator"
      minAllowed:
        {{- include "redis_operator_resources" . | nindent 8 }}
      maxAllowed:
        cpu: 100m
        memory: 256Mi
{{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-operator
  namespace: d8-operator-redis
  {{- include "helm_lib_module_labels" (list .) | nindent 2 }}
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: redis-operator
  template:
    metadata:
      labels:
        app: redis-operator
    spec:
      affinity:
      {{- include "helm_lib_node_selector" (tuple . "system") | nindent 6 }}
      {{- include "helm_lib_tolerations" (tuple . "system") | nindent 6 }}
      {{- include "helm_lib_priority_class" (tuple . "cluster-low") | nindent 6 }}
      {{- include "helm_lib_module_pod_security_context_run_as_user_nobody" . | nindent 6 }}
      containers:
      - image: {{ include "helm_lib_module_image" (list . "redisOperator") }}
        name: redis-operator
        {{- include "helm_lib_module_container_security_context_read_only_root_filesystem" . | nindent 8 }}
        ports:
          - name: metrics
            containerPort: 9710
            protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 9710
          initialDelaySeconds: 10
          periodSeconds: 3
          timeoutSeconds: 3
        livenessProbe:
          tcpSocket:
            port: 9710
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 6
          successThreshold: 1
        resources:
          requests:
            {{- include "helm_lib_module_ephemeral_storage_only_logs" . | nindent 12 }}
  {{- if not (.Values.global.enabledModules | has "vertical-pod-autoscaler-crd") }}
            {{- include "redis_operator_resources" . | nindent 12 }}
  {{- end }}
      serviceAccountName: operator-prometheus
      imagePullSecrets:
      - name: deckhouse-registry
---
apiVersion: v1
kind: Service
metadata:
  name: redis-operator
  namespace: d8-operator-redis
  {{- include "helm_lib_module_labels" (list . (dict "app" "redis-operator")) | nindent 2 }}
spec:
  clusterIP: None
  ports:
  - name: metrics
    port: 9710
    protocol: TCP
    targetPort: 9710
  selector:
    app: redis-operator
