---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  annotations:
    helm.sh/hook: post-upgrade, post-install
    helm.sh/hook-delete-policy: before-hook-creation
  name: redis-operator
  namespace: d8-operator-redis
  {{- include "helm_lib_module_labels" (list . (dict "app" "redis-operator")) | nindent 2 }}
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app: redis-operator
